name: publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish-main:
    uses: delameter/ci-cd/.github/workflows/publish-hatch.yml@v9
    with:
      python-version: "3.10"
      hatch-index-repo: "main"
    secrets:
      hatch-index-auth: ${{ secrets.PYPI_PASSWORD_MAIN }}
